name: Semantic release

on: push
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Build app
        run: npm run prod
      - name: Semantic release
        env:
          GITHUB_TOKEN: ${{ secrets.STYLEGUIDE_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.STYLEGUIDE_NPM_TOKEN }}
        run: npx semantic-release
